version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - mosquitto_volume:/mosquitto/data

  node-red:
    image: nodered/node-red
    container_name: mynodered
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - /Volumes/nvme_osx/docker_volumes/nodered_user_data:/data
#      - mynodered_volume:/var/lib/nodered

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=smarthome
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Mancika
    volumes:
      - /Volumes/nvme_osx/docker_volumes/influxdb_user_data:/var/lib/influxdb
      - ./influx-init.iql:/docker-entrypoint-initdb.d/

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
#      - telegraf_volume:/home
    depends_on: [influxdb]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - /Volumes/nvme_osx/docker_volumes/grafana_user_data:/var/lib/grafana

#volumes:
  #influxdb_volume: {}
  #grafana_volume: {}
  #mynodered_volume: {}
  #mosquitto_volume: {}
  #telegraf_volume: {}